# Generated by Django 4.1 on 2023-12-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_profile_name_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="recepient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET, to="chat.profile"
            ),
        ),
    ]
