# Generated by Django 4.1 on 2023-12-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_recepient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("timestamp",)},
        ),
    ]
