# Generated by Django 4.1 on 2023-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_recepient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="recepient",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
