# Generated by Django 4.1 on 2023-12-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_message_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.SET,
                related_name="messages",
                to="chat.profile",
            ),
            preserve_default=False,
        ),
    ]
